view-resolver:
  prefix: /
  suffix: .ftlh
freemarker:
  path: /templates

hikari:
  url: jdbc:postgresql://localhost:5432/oris-spring-2025
  username: postgres
  password: qwerty
  driver-class-name: org.postgresql.Driver
  max-pool-size: 16

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true
  hbm2ddl.auto: update
  enable_lazy_load_no_trans: true